server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/payroll_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata
    username: root
    password: "Spoorthib2003$"   # quoted because of $
  jpa:
    hibernate:
      ddl-auto: update           # dev: update | prod: validate
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: Asia/Kolkata

logging:
  level:
    org.hibernate.security: DEBUG

jwt:
  secret: "change-this-super-secret-256-bit-string-change-it"
  expiryMinutes: 120
